sensors:
    - id: "1"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: {{ value_json.value }}
      unit_of_measurement: V
      device_class: power
      friendly_name: net_consumption_voltage
    - id: "2"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: {{ value_json.value }}
      unit_of_measurement: W
      device_class: power
      friendly_name: net_comsumption_watt
