sensors:
    - id: "1"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.voltage
      unit_of_measurement: V
      device_class: power
      friendly_name: production_voltage
    - id: "2"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.actEnergyDlvd
      unit_of_measurement: Wh
      device_class: power
      friendly_name: production_actEnergyDlvd
    - id: "3"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.actEnergyRcvd
      unit_of_measurement: Wh
      device_class: power
      friendly_name: production_actEnergyRcvd
    - id: "4"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.activePower
      unit_of_measurement: W
      device_class: power
      friendly_name: production_activePower
    - id: "5"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.voltage
      unit_of_measurement: V
      device_class: power
      friendly_name: netconsumption_voltage
    - id: "6"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.actEnergyDlvd
      unit_of_measurement: Wh
      device_class: power
      friendly_name: netconsumption_actEnergyDlvd
    - id: "7"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.actEnergyRcvd
      unit_of_measurement: Wh
      device_class: power
      friendly_name: netconsumption_actEnergyRcvd
    - id: "8"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.activePower
      unit_of_measurement: W
      device_class: power
      friendly_name: netconsumption_activePower
