sensors:
    - id: "1"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.voltage
      unit_of_measurement: V
      device_class: power
      friendly_name: production_voltage_V
    - id: "2"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.actEnergyDlvd
      unit_of_measurement: kWh
      device_class: power
      friendly_name: production_actEnergyDlvd_kWh
    - id: "3"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.actEnergyRcvd
      unit_of_measurement: kWh
      device_class: power
      friendly_name: production_actEnergyRcvd_kWh
    - id: "4"
      state_class: measurement
      state_topic: EnvoyData/1
      value_template: value_json.activePower
      unit_of_measurement: W
      device_class: power
      friendly_name: production_activePower_W
    - id: "5"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.voltage
      unit_of_measurement: V
      device_class: power
      friendly_name: netconsumption_voltage_V
    - id: "6"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.actEnergyDlvd
      unit_of_measurement: kWh
      device_class: power
      friendly_name: netconsumption_actEnergyDlvd_kWh
    - id: "7"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.actEnergyRcvd
      unit_of_measurement: kWh
      device_class: power
      friendly_name: netconsumption_actEnergyRcvd_kWh
    - id: "8"
      state_class: measurement
      state_topic: EnvoyData/2
      value_template: value_json.activePower
      unit_of_measurement: W
      device_class: power
      friendly_name: netconsumption_activePower_W
